# This configuration is intended for development purpose, it's *your* responsibility to harden it for production
version: '3.8'
services:
  cheque-app:
    image: repo.sadad.co.ir/repository/baam-docker-registry/bmi/cheque-api:BUILD_NUMBER
    hostname: cheque-api
    container_name: ${CONTAINER_NAME}
    networks:
      cheque-api:
        aliases:
          - cheque-api-srv
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE},api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JVM_OPTS=-Dfile.encoding=UTF8
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - JAVA_OPTS= -agentlib:jdwp=transport=dt_socket,server=y,address=*:1020,suspend=n
    ports:
      - 8528:8081
      - 9521:1020
    tty: true
    working_dir: /
networks:
  cheque-api:
    driver: bridge
